apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    app: app1
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: {{ .Values.app1.servicePort }}
      targetPort: 5000
      nodePort: 30001
